### ISSUE TITLE
Github action om CDK versie te updaten en vervolgens een PR te maken

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/dns-management#10]
die PR moet wel de diff laten zien in cloudformation output zodat goed beoordeeld kan worden welke wijzigingen een update veroorzaakt.
Dat zou met de match snapshot functionaliteit van de test kunnen, maar misschien ook wel anders.

**Comment by marnixdessing** [comment]
Replaced by https://github.com/GemeenteNijmegen/cdk-repository-template/issues/2
