### ISSUE TITLE
vervanging certificaten tribebrp

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/dns-management#184]
-[x] CSR's aanmaken
-[ ] Validatierecords aanmaken
-[ ] certificaat vervangen

**Comment by WietekeNijmegen** [comment]
Er staat al een mooie issue bij wachten op derden. Kan ik irma van maken.

**Comment by joostvanderborg** [comment]
Vanochtend samen uitgevoerd
