### ISSUE TITLE
New AWS account for csp-nijmegen.nl (domain name & hosted zone)

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/dns-management#49]
We willen graag een nieuw AWS account om onze top level dns in te regelen.
We denken dat de beste naam voor het account 'dns' is.

De resources die daar in terecht komen zijn:
- De csp-nijmegen.nl hosted zone
- De csp-nijmegen.nl domein naam (AWS registar)
- Wellicht in de toekomst andere domein namen / hosted zones

**Comment by KaspervdG** [comment]
@marnixdessing ik ga er achteraan!
