### ISSUE TITLE
Aanvragen DNS wijzigingen app6 en app6-accp en mijn subdomeinen na dns verhuizing.

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/dns-management#58]

**Comment by marnixdessing** [comment]
app6-accp is aangevraagd

**Comment by marnixdessing** [comment]
app6-accp is aangepast en verwijst naar webformulieren.accp.csp-nijmegen.nl!

**Comment by joostvanderborg** [comment]
@marnixdessing mijn.nijmegen.nl is nu niet bereikbaar. Hiermee te maken?

**Comment by marnixdessing** [comment]
Het was een DNSSEC record dat de verkeerde waarde had in auth-prod.csp-nijmegen.nl.
