### ISSUE TITLE
License aanpassen naar EUPL v1.2

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/dns-management#7]

**Comment by marnixdessing** [comment]
Projen laat het niet toe om een andere license te gebruiken dan zij ondersteunen. 
* license optie haalt bij elke build een de license op uit de license library die in projen zit (EUPL zit daar nog niet in).
* licensed optie, om aan te geven dat er geen license wordt gebruikt verwijderd de license file bij elke build.

**Comment by marnixdessing** [comment]
Ik heb een PR gemaakt bij Projen (https://github.com/projen/projen/pull/1745). Hij is approved, nu is het waarschijnlijk wachten op de volgende release van Projen.

**Comment by marnixdessing** [comment]
Juiste license wordt gebruikt nu.
