### ISSUE TITLE
GitHub action om projen te updaten en daar een PR van te maken

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/dns-management#9]
die PR moet wel de diff laten zien in cloudformation output zodat goed beoordeeld kan worden welke wijzigingen een update veroorzaakt.
Dat zou met de match snapshot functionaliteit van de test kunnen, maar misschien ook wel anders.

**Comment by marnixdessing** [comment]
Replaced by https://github.com/GemeenteNijmegen/cdk-repository-template/issues/3
